"""Declarative base, naming conventions and model mixins (backlog E1.2).

Conventions (blueprint §E): UUIDv7 primary keys for business entities,
bigint identity for append-only/high-volume infrastructure tables,
``timestamptz`` everywhere, ``version`` for optimistic locking.
"""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, MetaData, Uuid, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import (
    DeclarativeBase,
    Mapped,
    Session,
    declared_attr,
    mapped_column,
    registry,
    scoped_session,
)

from app.core.clock import utcnow
from app.core.ids import new_id

DbSession = Session | scoped_session[Any]
"""A plain or scoped (Flask-SQLAlchemy ``db.session``) SQLAlchemy session."""

# Deterministic constraint/index names so Alembic migrations are stable.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    registry = registry(
        metadata=MetaData(naming_convention=NAMING_CONVENTION),
        type_annotation_map={
            datetime: DateTime(timezone=True),
            uuid.UUID: Uuid(as_uuid=True),
            dict[str, Any]: JSONB,
        },
    )


class UUIDPrimaryKeyMixin:
    """UUIDv7 primary key generated by the application (ADR-016, ADR-020)."""

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=new_id)


class TimestampMixin:
    """``created_at``/``updated_at`` from the injectable clock, with DB defaults as a backstop."""

    created_at: Mapped[datetime] = mapped_column(default=utcnow, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        default=utcnow, onupdate=utcnow, server_default=func.now()
    )


class VersionMixin:
    """Optimistic locking: SQLAlchemy adds ``WHERE version = :old`` to every UPDATE.

    A concurrent modification raises ``StaleDataError``, which the API maps to
    409 ``VERSION_CONFLICT``. Pair with ``core.concurrency.require_if_match``.
    """

    version: Mapped[int] = mapped_column(default=1, server_default="1")

    @declared_attr.directive
    def __mapper_args__(cls) -> dict[str, Any]:
        return {"version_id_col": cls.__table__.c.version}  # type: ignore[attr-defined]
