"""Application-generated UUIDv7 identifiers (RFC 9562 §5.7). See ADR-020.

Why this exists: Python 3.13 has no ``uuid.uuid7()`` (added in 3.14) and
PostgreSQL 16 has no ``uuidv7()`` (added in 18). This module is deliberately
self-contained so it can be swapped for the standard-library or database
implementation without touching callers: everything else calls ``new_id()``.

Layout (128 bits)::

    unix_ts_ms (48) | ver=0b0111 (4) | rand_a (12) | var=0b10 (2) | rand_b (62)

``rand_a`` is used as a 12-bit counter seeded randomly each millisecond
(RFC 9562 §6.2, Method 1), so ids generated by one process are strictly
increasing even within the same millisecond or if the wall clock steps back.

IMPORTANT: ordering between ids is a storage/index-locality property only. It
is NOT a business rule: ids from different processes can interleave, and code
must sort by explicit timestamp columns, never by id alone.
"""

import secrets
import threading
import time
import uuid
from collections.abc import Callable

_MAX_TIMESTAMP_MS = (1 << 48) - 1
_MAX_COUNTER = 0xFFF
# Seed the counter in the lower half of its range so a burst within one
# millisecond has headroom before it overflows (RFC 9562 §6.2 guidance).
_COUNTER_SEED_BITS = 11


def _system_time_ms() -> int:
    return time.time_ns() // 1_000_000


class UUIDv7Generator:
    """Thread-safe, per-process monotonic UUIDv7 generator."""

    def __init__(
        self,
        time_ms: Callable[[], int] = _system_time_ms,
        random_bits: Callable[[int], int] = secrets.randbits,
    ) -> None:
        self._time_ms = time_ms
        self._random_bits = random_bits
        self._lock = threading.Lock()
        self._last_ms = -1
        self._counter = 0

    def __call__(self) -> uuid.UUID:
        with self._lock:
            now_ms = self._time_ms()
            if now_ms > self._last_ms:
                self._last_ms = now_ms
                self._counter = self._random_bits(_COUNTER_SEED_BITS)
            else:
                # Same millisecond, or the clock moved backwards: keep the last
                # timestamp and advance the counter to stay monotonic.
                self._counter += 1
                if self._counter > _MAX_COUNTER:
                    # Counter exhausted: borrow the next millisecond (RFC 9562 §6.2).
                    self._last_ms += 1
                    self._counter = self._random_bits(_COUNTER_SEED_BITS)
            timestamp_ms = self._last_ms
            counter = self._counter

        if not 0 <= timestamp_ms <= _MAX_TIMESTAMP_MS:
            raise ValueError("timestamp out of range for UUIDv7")
        rand_b = self._random_bits(62)
        value = (
            (timestamp_ms << 80)
            | (0x7 << 76)  # version 7
            | (counter << 64)
            | (0b10 << 62)  # RFC 9562 variant
            | rand_b
        )
        return uuid.UUID(int=value)


def timestamp_ms(value: uuid.UUID) -> int:
    """Return the embedded Unix timestamp (milliseconds) of a UUIDv7."""
    if value.version != 7:
        raise ValueError("not a UUIDv7")
    return value.int >> 80


new_id: Callable[[], uuid.UUID] = UUIDv7Generator()
"""Generate a new UUIDv7. The single entry point used by the rest of the code."""
